apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/your-repo.git'
    path: ''  # No specific path needed for existing applications
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  resource:
    # Include existing applications as resources
    resources:
      - apiVersion: argoproj.io/v1alpha1
        kind: Application
        name: micro-service-1
        namespace: argocd
      - apiVersion: argoproj.io/v1alpha1
        kind: Application
        name: micro-service-2
        namespace: argocd
      - apiVersion: argoproj.io/v1alpha1
        kind: Application
        name: micro-service-3
        namespace: argocd
